name: aurora

# General
batch_size: 256

# GA emitter
iso_sigma: 0.005
line_sigma: 0.05

# AE
features: 128
hidden_size: 6

train_ratio: 8
lr_init_value: 5e-4
lr_end_value: 0.
lr_transition_steps: 0
lr_transition_begin: 0
ae_batch_size: 256

# Search space
policy_hidden_layer_sizes: [64, 64]
